
services:
  api:
    build: ./
    container_name: api-user-service
    working_dir: /src
    command: >
      sh -c "uvicorn main:app --host ${HOST} --port ${HOST_PORT}"
    networks:
      - my-network
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    depends_on:
      - db
    env_file:
      - .env-non-dev



  db:
    image: postgres:14
    container_name: db-user-service
    command: -p 5435
    networks:
      - my-network
    ports:
      - "${DB_PORT}:5435"
    expose:
      - "${DB_PORT}"
    env_file:
      - .env-non-dev



networks:
  my-network:
    driver: bridge
    external: true