version: '3.8'

services:
  web:
    build: ./
    container_name: fastapi_app
    command: bash -c 'uvicorn main:app --host 0.0.0.0 --port 8000'
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env-non-dev


  db:
    image: postgres:14
    container_name: postgres_db
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env-non-dev


