
services:
  api:
    build: ../.
    container_name: api-user-service-ci-cd
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    depends_on:
      - db
    env_file:
      - $env

  db:
    image: postgres:14
    container_name: db-user-service-ci-cd
    command: -p 5435
    ports:
      - "${DB_PORT}:5435"
    expose:
      - "${DB_PORT}"
    env_file:
      - $env

