
services:
  web:
    build: ../.
    container_name: app
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - $env
    command: ["pytest", "tests"]


  db:
    image: postgres:14
    container_name: database
    command: -p 5435
    expose:
      - 5435
    env_file:
      - $env


